from pathlib import Path
import re
import uuid

from langchain_pymupdf4llm import PyMuPDF4LLMLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter


# ============================================================
# PATHS
# ============================================================

DATA_DIR = Path(__file__).resolve().parent / "data"
PDF_PATH = DATA_DIR / "Divergent.pdf"

BOOK_NAME = "Divergent"


# ============================================================
# CHUNKING CONFIGURATION
# ============================================================

# These are approximate token targets.
#
# RecursiveCharacterTextSplitter works with characters,
# not tokens.
#
# Rough English approximation:
#
#     4 characters ≈ 1 token
#
# Parent:
#     6000 characters ≈ 1500 tokens
#     600 character overlap ≈ 150 tokens
#
# Child:
#     1400 characters ≈ 350 tokens
#     200 character overlap ≈ 50 tokens

PARENT_CHUNK_SIZE = 6000
PARENT_CHUNK_OVERLAP = 600

CHILD_CHUNK_SIZE = 1400
CHILD_CHUNK_OVERLAP = 200


# ============================================================
# TEXT SPLITTER SEPARATORS
# ============================================================

SEPARATORS = [
    "\n\n",
    "\n",
    ". ",
    "? ",
    "! ",
    " ",
    ""
]


# ============================================================
# LOAD PDF
# ============================================================

def load_book():
    """
    Load the PDF using PyMuPDF4LLM.

    mode='page' keeps the original PDF pages separate,
    which allows us to preserve page metadata.
    """

    print(f"Loading: {PDF_PATH}")

    loader = PyMuPDF4LLMLoader(
        str(PDF_PATH),
        mode="page"
    )

    documents = loader.load()

    print(f"Pages loaded: {len(documents)}")

    return documents


# ============================================================
# TEXT CLEANING
# ============================================================

def clean_text(text):
    """
    Clean PDF-extracted text while preserving paragraph
    structure.

    We intentionally DO NOT remove newlines completely,
    because paragraph boundaries are useful when chunking
    a novel.
    """

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Normalize spaces and tabs.
    text = re.sub(r"[ \t]+", " ", text)

    # Remove excessive blank lines.
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


# ============================================================
# CHAPTER DETECTION
# ============================================================

def normalize_heading_line(line):
    """
    Remove common Markdown formatting generated by
    PyMuPDF4LLM.

    Examples:

        # Chapter One
        # **Chapter One**
        **Chapter One**
        Chapter One

    become approximately:

        Chapter One
    """

    line = line.strip()

    # Remove Markdown heading markers.
    line = re.sub(r"^#{1,6}\s*", "", line)

    # Remove bold markers.
    line = line.replace("**", "")

    # Remove surrounding whitespace.
    line = line.strip()

    return line


def match_chapter_line(line):
    """
    Check whether one line looks exactly like a chapter heading.

    Supports:

        Chapter One
        Chapter Twenty-Six
        Chapter 1
        # Chapter One
        # **Chapter One**
        **Chapter One**
    """

    normalized = normalize_heading_line(line)

    pattern = re.compile(
        r"^Chapter\s+([A-Za-z]+(?:[-\s][A-Za-z]+)*|\d+)$",
        re.IGNORECASE
    )

    match = pattern.match(normalized)

    if not match:
        return None

    chapter_value = match.group(1).strip()

    return f"Chapter {chapter_value}"


def find_chapter_heading(text):
    """
    Find a genuine chapter heading on a page.

    Important:
    A Table of Contents can contain many lines such as:

        Chapter One
        Chapter Two
        Chapter Three

    Therefore, we do not simply search for the first
    occurrence of 'Chapter X'.

    We first detect whether the page looks like a
    contents page and reject it.
    """

    lines = [
        line.strip()
        for line in text.splitlines()
        if line.strip()
    ]

    chapter_candidates = []

    for index, line in enumerate(lines):

        chapter = match_chapter_line(line)

        if chapter:
            chapter_candidates.append(
                (index, chapter)
            )

    # --------------------------------------------------------
    # If there are many chapter headings on one page,
    # this is almost certainly a Table of Contents.
    # --------------------------------------------------------

    if len(chapter_candidates) >= 3:
        return None

    # --------------------------------------------------------
    # A normal chapter page should have one chapter heading.
    # --------------------------------------------------------

    if len(chapter_candidates) == 1:

        line_index, chapter = chapter_candidates[0]

        # A real chapter heading should occur reasonably
        # close to the beginning of the page.
        #
        # This prevents a random "Chapter X" appearing
        # deep inside a page from being interpreted as
        # a new chapter.
        if line_index <= 12:
            return chapter

    return None


# ============================================================
# FRONT MATTER / CONTENTS DETECTION
# ============================================================

def is_contents_page(text):
    """
    Detect obvious Table of Contents pages.
    """

    lower = text.lower()

    contents_indicators = [
        "contents",
        "table of contents"
    ]

    return any(
        indicator in lower
        for indicator in contents_indicators
    )


def is_front_matter_page(text):
    """
    Detect obvious front-matter pages.

    This function is only used BEFORE the first real
    chapter has been detected.

    Once the novel has started, we do not discard pages
    based on these words.
    """

    lower = text.lower()

    front_matter_indicators = [
        "contents",
        "table of contents",
        "dedication",
        "copyright",
        "all rights reserved",
        "published by"
    ]

    return any(
        indicator in lower
        for indicator in front_matter_indicators
    )

def is_supplementary_material(text):
    """
    Detect material that comes after the Divergent novel.

    The PDF contains an excerpt from Insurgent after
    Chapter Thirty-Nine, followed by other supplementary
    pages such as acknowledgments and author information.

    These pages should not be included in the Divergent RAG corpus.
    """

    lower = text.lower()

    supplementary_markers = [
        "excerpt from insurgent",
        "acknowledgments",
        "about the author",
        "back ad",
        "praise for divergent",
        "books by veronica roth",
        "credits",
        "about the publisher",
    ]

    return any(
        marker in lower
        for marker in supplementary_markers
    )


# ============================================================
# PAGE PROCESSING
# ============================================================

def create_page_documents(documents):
    """
    Convert raw PDF documents into cleaned page records.

    Everything before the first genuine chapter is treated
    as front matter and ignored.

    After the first chapter is found, every page inherits
    the current chapter until another chapter heading is
    detected.
    """

    processed_pages = []

    current_chapter = None
    book_started = False

    print("\nDetecting chapter boundaries...")

    for document in documents:

        text = clean_text(
            document.page_content
        )

        if not text:
            continue

        page_number = document.metadata.get("page")

        # ====================================================
        # BEFORE THE NOVEL STARTS
        # ====================================================

        if not book_started:

            # Explicitly ignore Contents pages.
            if is_contents_page(text):
                continue

            # Try to detect a genuine chapter.
            detected_chapter = find_chapter_heading(text)

            if detected_chapter:

                current_chapter = detected_chapter
                book_started = True

                print(
                    f"Detected {current_chapter} "
                    f"on PDF page {page_number}"
                )

            else:
                # Still in front matter.
                continue

        # ====================================================
        # AFTER THE NOVEL HAS STARTED
        # ====================================================

        else:

            detected_chapter = find_chapter_heading(text)

            if detected_chapter:

                current_chapter = detected_chapter

                print(
                    f"Detected {current_chapter} "
                    f"on PDF page {page_number}"
                )

        # ====================================================
        # STORE PAGE
        # ====================================================

        processed_pages.append({
            "text": text,
            "page": page_number,
            "chapter": current_chapter
        })

    return processed_pages


# ============================================================
# GROUP PAGES INTO CHAPTERS
# ============================================================

def create_chapters(pages):
    """
    Group consecutive pages into chapters.

    Result:

        BOOK
          |
          +-- Chapter One
          |      |
          |      +-- continuous chapter text
          |
          +-- Chapter Two
          |      |
          |      +-- continuous chapter text
          |
          +-- Chapter Three
                 |
                 +-- continuous chapter text
    """

    chapters = []

    current_chapter = None
    current_pages = []
    current_text_parts = []

    for page in pages:

        chapter = page["chapter"]

        # ----------------------------------------------------
        # First chapter
        # ----------------------------------------------------

        if current_chapter is None:
            current_chapter = chapter

        # ----------------------------------------------------
        # New chapter detected
        # ----------------------------------------------------

        if chapter != current_chapter:

            if current_text_parts:

                chapters.append({
                    "chapter": current_chapter,
                    "pages": current_pages.copy(),
                    "text": "\n\n".join(
                        current_text_parts
                    )
                })

            current_chapter = chapter
            current_pages = []
            current_text_parts = []

        # ----------------------------------------------------
        # Add current page
        # ----------------------------------------------------

        current_pages.append(
            page["page"]
        )

        current_text_parts.append(
            page["text"]
        )

    # --------------------------------------------------------
    # Add final chapter
    # --------------------------------------------------------

    if current_text_parts:

        chapters.append({
            "chapter": current_chapter,
            "pages": current_pages.copy(),
            "text": "\n\n".join(
                current_text_parts
            )
        })

    return chapters


# ============================================================
# PARENT CHUNKS
# ============================================================

def create_parent_chunks(chapters):
    """
    Split each chapter into parent chunks.

    IMPORTANT:

    Parents are created from the COMPLETE CHAPTER TEXT.

    Therefore a parent is allowed to cross a PDF page
    boundary, but it can NEVER cross a chapter boundary.
    """

    parent_splitter = RecursiveCharacterTextSplitter(
        chunk_size=PARENT_CHUNK_SIZE,
        chunk_overlap=PARENT_CHUNK_OVERLAP,
        separators=SEPARATORS
    )

    parents = []

    for chapter_index, chapter in enumerate(chapters):

        chunks = parent_splitter.split_text(
            chapter["text"]
        )

        for parent_index, chunk in enumerate(chunks):

            parent_id = str(
                uuid.uuid4()
            )

            parents.append({
                "id": parent_id,

                "text": chunk,

                "metadata": {
                    "book": BOOK_NAME,
                    "source": str(PDF_PATH),

                    # Hierarchy
                    "level": "parent",

                    # Chapter information
                    "chapter": chapter["chapter"],
                    "chapter_index": chapter_index,

                    # Parent information
                    "parent_index": parent_index,

                    # Chapter page range
                    "chapter_page_start": min(
                        chapter["pages"]
                    ),
                    "chapter_page_end": max(
                        chapter["pages"]
                    )
                }
            })

    return parents


# ============================================================
# CHILD CHUNKS
# ============================================================

def create_child_chunks(parents):
    """
    Split each parent into smaller child chunks.

    Children are the chunks that will eventually be embedded
    and stored in Qdrant.

    Each child maintains a parent_id so that retrieval can
    later expand:

        child -> parent
    """

    child_splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHILD_CHUNK_SIZE,
        chunk_overlap=CHILD_CHUNK_OVERLAP,
        separators=SEPARATORS
    )

    children = []

    for parent in parents:

        child_chunks = child_splitter.split_text(
            parent["text"]
        )

        for child_index, child_text in enumerate(
            child_chunks
        ):

            child_id = str(
                uuid.uuid4()
            )

            children.append({
                "id": child_id,

                "text": child_text,

                "metadata": {
                    "book": BOOK_NAME,
                    "source": parent["metadata"]["source"],

                    # Hierarchy
                    "level": "child",

                    # Parent relationship
                    "parent_id": parent["id"],

                    # Chapter information
                    "chapter": parent["metadata"]["chapter"],
                    "chapter_index": parent["metadata"]["chapter_index"],

                    # Position
                    "parent_index": parent["metadata"]["parent_index"],
                    "child_index": child_index,

                    # Chapter page range
                    "chapter_page_start": parent["metadata"]["chapter_page_start"],
                    "chapter_page_end": parent["metadata"]["chapter_page_end"]
                }
            })

    return children


# ============================================================
# STATISTICS
# ============================================================

def calculate_chunk_statistics(chunks):
    """
    Calculate basic character-based statistics.

    Character counts are used because the splitter is
    character-based.
    """

    if not chunks:
        return {
            "count": 0,
            "average": 0,
            "minimum": 0,
            "maximum": 0
        }

    lengths = [
        len(chunk["text"])
        for chunk in chunks
    ]

    return {
        "count": len(lengths),
        "average": sum(lengths) / len(lengths),
        "minimum": min(lengths),
        "maximum": max(lengths)
    }


def print_statistics(
    pages,
    chapters,
    parents,
    children
):
    """
    Print useful diagnostics for evaluating the chunking
    stage.
    """

    parent_stats = calculate_chunk_statistics(
        parents
    )

    child_stats = calculate_chunk_statistics(
        children
    )

    print("\n" + "=" * 60)
    print("CHUNKING STATISTICS")
    print("=" * 60)

    print(f"Book:                  {BOOK_NAME}")

    print(f"Pages loaded:          {len(pages)}")
    print(f"Chapters:              {len(chapters)}")
    print(f"Parents:               {len(parents)}")
    print(f"Children:              {len(children)}")

    if parents:
        children_per_parent = (
            len(children) / len(parents)
        )

        print(
            f"Children / parent:    "
            f"{children_per_parent:.2f}"
        )

    print("\nParent chunk sizes (characters):")

    print(
        f"  Average:             "
        f"{parent_stats['average']:.0f}"
    )

    print(
        f"  Minimum:             "
        f"{parent_stats['minimum']}"
    )

    print(
        f"  Maximum:             "
        f"{parent_stats['maximum']}"
    )

    print("\nChild chunk sizes (characters):")

    print(
        f"  Average:             "
        f"{child_stats['average']:.0f}"
    )

    print(
        f"  Minimum:             "
        f"{child_stats['minimum']}"
    )

    print(
        f"  Maximum:             "
        f"{child_stats['maximum']}"
    )

    print("\nChapter sizes:")

    for chapter in chapters:

        character_count = len(
            chapter["text"]
        )

        approximate_tokens = (
            character_count / 4
        )

        print(
            f"  {chapter['chapter']:<25} "
            f"{character_count:>8,} chars "
            f"(~{approximate_tokens:,.0f} tokens)"
        )


# ============================================================
# PRINT CHAPTER BOUNDARIES
# ============================================================

def print_chapter_boundaries(chapters):
    """
    Print the chapter/page mapping.

    This is extremely useful for checking whether chapter
    detection is working correctly.
    """

    print("\n" + "=" * 60)
    print("CHAPTER BOUNDARIES")
    print("=" * 60)

    for index, chapter in enumerate(chapters):

        print(
            f"{index:>3}: "
            f"{chapter['chapter']:<25} "
            f"PDF pages "
            f"{min(chapter['pages'])} - "
            f"{max(chapter['pages'])}"
        )


# ============================================================
# PRINT EXAMPLES
# ============================================================

def print_examples(
    chapters,
    parents,
    children
):
    """
    Display examples from the generated hierarchy.
    """

    # --------------------------------------------------------
    # Chapter
    # --------------------------------------------------------

    if chapters:

        print("\n" + "=" * 60)
        print("EXAMPLE CHAPTER")
        print("=" * 60)

        chapter = chapters[0]

        print(
            f"{chapter['chapter']}"
        )

        print(
            f"Pages: "
            f"{min(chapter['pages'])} - "
            f"{max(chapter['pages'])}"
        )

        print("\nText preview:\n")

        print(
            chapter["text"][:2000]
        )

    # --------------------------------------------------------
    # Parent
    # --------------------------------------------------------

    if parents:

        print("\n" + "=" * 60)
        print("EXAMPLE PARENT")
        print("=" * 60)

        print(
            parents[0]["text"]
        )

        print("\nMetadata:")

        print(
            parents[0]["metadata"]
        )

    # --------------------------------------------------------
    # Child
    # --------------------------------------------------------

    if children:

        print("\n" + "=" * 60)
        print("EXAMPLE CHILD")
        print("=" * 60)

        print(
            children[0]["text"]
        )

        print("\nMetadata:")

        print(
            children[0]["metadata"]
        )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # 1. LOAD
    # --------------------------------------------------------

    documents = load_book()

    # --------------------------------------------------------
    # 2. CLEAN + DETECT CHAPTERS
    # --------------------------------------------------------

    print(
        "\nCleaning pages and detecting chapters..."
    )

    pages = create_page_documents(
        documents
    )

    print(
        f"\nUsable pages: {len(pages)}"
    )

    # --------------------------------------------------------
    # Safety check
    # --------------------------------------------------------

    if not pages:

        print(
            "\nERROR: No novel pages were detected."
        )

        print(
            "Chapter detection needs to be adjusted "
            "for this PDF."
        )

        raise SystemExit(1)

    # --------------------------------------------------------
    # 3. GROUP PAGES INTO CHAPTERS
    # --------------------------------------------------------

    print(
        "\nGrouping pages into chapters..."
    )

    chapters = create_chapters(
        pages
    )

    print(
        f"Chapters detected: {len(chapters)}"
    )

    # --------------------------------------------------------
    # Safety check
    # --------------------------------------------------------

    if len(chapters) < 2:

        print(
            "\nWARNING:"
        )

        print(
            "Very few chapters were detected."
        )

        print(
            "Check the CHAPTER BOUNDARIES output below."
        )

    # --------------------------------------------------------
    # 4. CREATE PARENTS
    # --------------------------------------------------------

    print(
        "\nCreating parent chunks..."
    )

    parents = create_parent_chunks(
        chapters
    )

    print(
        f"Parents created: {len(parents)}"
    )

    # --------------------------------------------------------
    # 5. CREATE CHILDREN
    # --------------------------------------------------------

    print(
        "\nCreating child chunks..."
    )

    children = create_child_chunks(
        parents
    )

    print(
        f"Children created: {len(children)}"
    )

    # --------------------------------------------------------
    # 6. STATISTICS
    # --------------------------------------------------------

    print_statistics(
        pages,
        chapters,
        parents,
        children
    )

    # --------------------------------------------------------
    # 7. CHAPTER BOUNDARIES
    # --------------------------------------------------------

    print_chapter_boundaries(
        chapters
    )

    # --------------------------------------------------------
    # 8. EXAMPLES
    # --------------------------------------------------------

    print_examples(
        chapters,
        parents,
        children
    )